version: 2.1
jobs: # ジョブの設定を追加
  test:
    docker: # エグゼキューター
      - image: cimg/node:18.14.0
    parallelism: 2 # 並列数2で実行
    steps: # Jobで実行されるステップ
      - checkout # Githubからソースコードをチェックアウトする
      - restore_cache: # キャッシュの取得
          keys:
          - node-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install node packages # 依存関係のインストール
          command: npm install
      - save_cache: # キャッシュの保存
          paths:
            - ./node_modules
          key: node-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Run lint and format # lint and format
          command: npm run lint && npm run format
      - run:
          name: Run Test # UIとE2E以外のテストを実行
          # command: npm test -- src/chapter2/start src/chapter2/assertion src/chapter2/group src/chapter2/mock
          # CircleCI CLIでテストを分割
          # 今回はUIテスト、E2Eを除外したいのでjest --listTestsコマンドで指定したディレクトリのテストファイルを抽出
          # command: |
          #   TEST_FILES=$(npx jest --listTests src/chapter2/start src/chapter2/assertion src/chapter2/group src/chapter2/mock | circleci tests split)
          #   echo $TEST_FILES
          #   npm test -- $TEST_FILES
          command: | # Jestのshardオブションでテストを分割
            npm test -- --shard=$(($CIRCLE_NODE_INDEX+1))/$CIRCLE_NODE_TOTAL src/chapter2/start src/chapter2/assertion src/chapter2/group src/chpater2/mock
      - store_test_results: # テスト結果をアップロード
          path: reports/Jest
      - store_artifacts: # カバレッジをアップロード
          path: reports/coverage
  ui-test:
    docker:
      - image: cimg/node:18.14.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v2-{{ checksum "package-lock.json" }}
      - run:
          name: Install node packages
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-v2-{{ checksum "package-lock.json" }}
      - run:
          name: Run lint and format # lint and format
          command: npm run lint && npm run format
      - run:
          name: Run UI Test
          command: npm test -- src/chapter2/ui
      - run:
          name: Upload Storybook to Chromatic # ChromaticへStorybookをアップロードする
          command: npm run chromatic
workflows: # ワークフローの設定を追加
  test:
    jobs:
      - test
      - ui-test
